name: Common CI - Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2

    - name: Node.js Setup
      uses: actions/setup-node@v2
      with:
        node-version: lts/gallium
    - name: Installation of Node.js dependencies
      run: npm i